begin;
set local role service_role;
do $test$
declare
 b uuid:=gen_random_uuid(); svc uuid:=gen_random_uuid(); campaign uuid:=gen_random_uuid(); promo uuid:=gen_random_uuid(); q uuid:=gen_random_uuid();
 request_id uuid:=gen_random_uuid(); test_day date:=(now() at time zone 'America/Mexico_City')::date+1;
 start_time timestamptz; sess text; sess2 text; result jsonb; again jsonb; p jsonb; booked uuid; patient1 uuid; token text:=repeat('a',64); qr_token text:=encode(extensions.gen_random_bytes(16),'hex');
 n integer;
begin
 insert into public.branches(id,name,slug,booking_enabled) values(b,'TEST ONLY','test-'||b::text,true);
 insert into public.services(id,name,slug,price,duration_minutes) values(svc,'TEST ONLY','test-'||svc::text,100,30);
 insert into public.branch_services(branch_id,service_id) values(b,svc);
 insert into public.branch_hours(branch_id,weekday,opens_at,closes_at,slot_minutes,capacity) values(b,extract(dow from test_day)::int,'09:00','10:00',15,1);
 insert into public.campaigns(id,name) values(campaign,'TEST ONLY');
 insert into public.promo_codes(id,code,name,discount_type,discount_value,usage_limit,campaign_id) values(promo,'T-'||promo::text,'TEST ONLY','percentage',50,1,campaign);
 insert into public.qr_codes(id,name,promo_code_id,campaign_id,token) values(q,'TEST ONLY',promo,campaign,qr_token);
 start_time:=(test_day+time '09:00') at time zone 'America/Mexico_City';
 select count(*) into n from public.gateway_slots(b,svc,test_day);
 if n<>3 then raise exception 'Expected 3 slots, got %',n; end if;
 sess:=public.gateway_track(null,'qr_scanned',qr_token)->>'token';
 perform public.gateway_track(sess,'qr_scanned',qr_token);
 perform public.gateway_track(sess,'landing_viewed');
 perform public.gateway_track(sess,'service_selected',null,b,svc);
 perform public.gateway_track(sess,'appointment_started',null,b,svc);
 perform public.gateway_track(sess,'landing_viewed');
 if (select last_stage from public.tracking_sessions where anonymous_token=encode(extensions.digest(sess,'sha256'),'hex'))<>'appointment_started' then raise exception 'Reload regressed funnel progress';end if;
 if (select count(*) from public.tracking_events where qr_id=q and event_type='qr_scanned')<>2 then raise exception 'Scan count'; end if;
 if (select count(distinct session_id) from public.tracking_events where qr_id=q and event_type='qr_scanned')<>1 then raise exception 'Unique visitors'; end if;
 p:=jsonb_build_object('branch_id',b,'service_id',svc,'starts_at',start_time,'request_id',request_id,'management_token',token,'session_token',sess,'name','TEST PATIENT','phone','5555555555','privacy_accepted',true,'promo_code','T-'||promo::text);
 begin perform public.gateway_book(p||jsonb_build_object('privacy_accepted',false));raise exception 'Expected privacy rejection';exception when others then if sqlerrm<>'PRIVACY_REQUIRED' then raise; end if;end;
 begin perform public.gateway_book(p||jsonb_build_object('starts_at',start_time+interval '5 minutes'));raise exception 'Expected off-grid rejection';exception when others then if sqlerrm<>'SLOT_UNAVAILABLE' then raise; end if;end;
 begin perform public.gateway_book(p||jsonb_build_object('starts_at',start_time+interval '45 minutes'));raise exception 'Expected closing rejection';exception when others then if sqlerrm<>'SLOT_UNAVAILABLE' then raise; end if;end;
 result:=public.gateway_book(p);booked:=(result->>'appointment_id')::uuid;
 if (result->>'quoted_total')::numeric<>50 then raise exception 'Promotion calculation'; end if;
 again:=public.gateway_book(p);if again<>result then raise exception 'Idempotency';end if;
 if public.gateway_lookup(result->>'folio',repeat('b',64)) is not null then raise exception 'Wrong token leaked booking';end if;
 if public.gateway_lookup(result->>'folio',token) is null then raise exception 'Correct token denied';end if;
 if (select count(*) from public.gateway_slots(b,svc,test_day))<>1 then raise exception 'Overlap not removed';end if;
 if (select campaign_id from public.tracking_sessions where appointment_id=booked)<>campaign then raise exception 'Attribution lost';end if;
 if (select count(*) from public.tracking_events where appointment_id=booked and event_type='appointment_completed')<>1 then raise exception 'Conversion duplicated';end if;
 sess2:=public.gateway_track(null,'landing_viewed')->>'token';
 p:=p||jsonb_build_object('request_id',gen_random_uuid(),'session_token',sess2);
 begin perform public.gateway_book(p);raise exception 'Expected capacity rejection';exception when others then if sqlerrm<>'SLOT_UNAVAILABLE' then raise;end if;end;
 p:=p||jsonb_build_object('starts_at',start_time+interval '30 minutes');
 begin perform public.gateway_book(p);raise exception 'Expected exhausted promo rejection';exception when others then if sqlerrm<>'PROMO_EXHAUSTED' then raise;end if;end;
 p:=p||jsonb_build_object('promo_code','');again:=public.gateway_book(p);
 select patient_id into patient1 from public.appointments where id=booked;
 if (select patient_id from public.appointments where id=(again->>'appointment_id')::uuid)=patient1 then raise exception 'Patients incorrectly merged by phone';end if;
 if (select count(*) from public.gateway_slots(b,svc,test_day))<>0 then raise exception 'Capacity exceeded';end if;
 if public.gateway_rate_limit('test-'||b::text,1,60) is not true or public.gateway_rate_limit('test-'||b::text,1,60) is not false then raise exception 'Rate limiter';end if;
 if not exists(select 1 from public.audit_logs where entity_id=booked::text and action='INSERT') then raise exception 'Missing audit';end if;
end $test$;
reset role;
do $test$ begin
 if has_function_privilege('anon','public.gateway_book(jsonb)','execute') or has_function_privilege('authenticated','public.gateway_book(jsonb)','execute') then raise exception 'Booking bypass privilege';end if;
 if has_function_privilege('anon','public.book_appointment(text,text,text,uuid,uuid,timestamptz,text,text,text)','execute') then raise exception 'Legacy bypass';end if;
end $test$;
select 'PASS: slots, alignment, closing, privacy, discounts, limits, overlap, idempotency, token lookup, attribution, unique sessions, patient separation, rate limiting, audit and RPC grants' as result;
rollback;
