import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireStaff} from '@/lib/auth';
import {can} from '@/lib/access';
import {states,todayMX,validDate} from '@/lib/calendar';
import {updateAppointment,checkIn,reschedule} from '../../appointment-actions';
import {SubmitButton} from '@/components/submit-button';
export default async function Detail({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
 const {id}=await params;const q=await searchParams;if(!/^[a-f0-9-]{36}$/i.test(id))notFound();const {supabase,profile}=await requireStaff('clinical:read');
 const {data:a,error}=await supabase.from('appointments').select('id,folio,starts_at,ends_at,status,checked_in_at,quoted_total,attributed_revenue,patients(full_name,phone,email),branches(name,timezone),appointment_services(services(name,preparation))').eq('id',id).maybeSingle();if(error)throw Error('No se pudo cargar la cita.');if(!a)notFound();
 const row=a as any;const writable=can(profile.role,'clinical:write');const open=['pending','confirmed'].includes(a.status);let slots:any[]=[];let slotError=false;
 if(writable&&open&&q.date&&validDate(q.date)){const r=await supabase.rpc('staff_slots',{p_id:id,p_date:q.date});slots=r.data||[];slotError=!!r.error;}
 return <main className="work-page"><Link href="/admin/agenda" className="quiet-link">← Volver a agenda</Link><div className="page-heading"><p className="eyebrow">DETALLE DE CITA</p><h1>{a.folio}</h1><span className="status-pill">{states[a.status]}</span></div>{q.error&&<p className="form-alert" role="alert">{q.error}</p>}{q.saved&&<p role="status" className="success-note">Cambios guardados.</p>}
 <div className="work-grid"><section className="card panel-pad"><h2>{row.patients?.full_name}</h2><p>{row.patients?.phone} · {row.patients?.email||'Sin correo registrado'}</p><h3>{row.branches?.name}</h3><p>{new Date(a.starts_at).toLocaleString('es-MX',{timeZone:row.branches?.timezone||'America/Mexico_City'})}</p><p>Importe cotizado: {a.quoted_total===null?'Por confirmar':Number(a.quoted_total).toLocaleString('es-MX',{style:'currency',currency:'MXN'})}</p>{row.appointment_services?.map((s:any)=><div key={s.services?.name}><strong>{s.services?.name}</strong><p>{s.services?.preparation||'Confirma la preparación con la sucursal.'}</p></div>)}{a.checked_in_at&&<p className="success-note">Llegada registrada: {new Date(a.checked_in_at).toLocaleTimeString('es-MX',{timeZone:row.branches?.timezone})}</p>}
 {writable&&open&&!a.checked_in_at&&<form action={checkIn}><input type="hidden" name="id" value={id}/><SubmitButton>Registrar llegada hoy</SubmitButton></form>}</section>
 {writable&&<section className="card panel-pad"><h2>Seguimiento de atención</h2>{(open||a.status==='attended')?<form action={updateAppointment} className="form-stack"><input type="hidden" name="id" value={id}/><input type="hidden" name="detail" value="1"/><label>Estado<select name="status" defaultValue={a.status==='attended'?'attended':'confirmed'}>{['confirmed','attended','cancelled','no_show'].filter(s=>a.status!=='attended'||s==='attended').map(s=><option key={s} value={s}>{states[s]}</option>)}</select></label><label>Ingreso recibido, solo al marcar atendida (MXN)<input name="revenue" type="number" min="0" max="10000000" step="0.01" placeholder="Vacío conserva el importe registrado"/></label><label className="check-label"><input type="checkbox" required/>Confirmo el cambio de estado.</label><SubmitButton>Guardar seguimiento</SubmitButton></form>:<p>Esta cita está cerrada y conserva su historial.</p>}</section>}
 </div>{writable&&open&&<section className="card panel-pad section-space"><h2>Reprogramar sin perder el folio</h2><p>La disponibilidad se comprueba de nuevo al guardar. Horarios en la zona local de la sucursal.</p><form className="filter-bar"><label>Nueva fecha<input type="date" name="date" required defaultValue={q.date||todayMX()}/></label><button className="button button-secondary">Buscar horarios</button></form>{slotError?<p role="alert">No se pudo consultar la disponibilidad.</p>:q.date&&(!slots.length?<p>No hay horarios disponibles. Revisa la configuración o elige otra fecha.</p>:<form action={reschedule} className="form-stack"><input type="hidden" name="id" value={id}/><label>Horario disponible<select name="starts_at" required>{slots.map(s=><option value={s.starts_at} key={s.starts_at}>{new Date(s.starts_at).toLocaleTimeString('es-MX',{timeZone:row.branches?.timezone,hour:'2-digit',minute:'2-digit'})} · {s.remaining} lugares</option>)}</select></label><SubmitButton>Confirmar reprogramación</SubmitButton></form>)}</section>}</main>;
}
