import Link from 'next/link';
import {requireStaff} from '@/lib/auth';
import {dateRange,todayMX,TZ,addDays,states} from '@/lib/calendar';
export default async function Agenda({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const q=await searchParams;const {supabase}=await requireStaff('clinical:read');const week=q.view==='week';const {from,to,days}=dateRange(q.date||todayMX(),week);
 let req=supabase.from('appointments').select('id,folio,starts_at,status,checked_in_at,patients(full_name),branches(name)').gte('starts_at',from+'T00:00:00-06:00').lt('starts_at',to+'T00:00:00-06:00').order('starts_at').limit(501);
 if(q.branch&&/^[a-f0-9-]{36}$/i.test(q.branch))req=req.eq('branch_id',q.branch);
 const [r,b]=await Promise.all([req,supabase.from('branches').select('id,name').eq('active',true).order('name')]);if(r.error||b.error)throw Error('No se pudo cargar la agenda.');
 const rows=(r.data||[]).slice(0,500);const url=(date:string,view=week?'week':'day')=>'/admin/agenda?'+new URLSearchParams({date,view,...(q.branch?{branch:q.branch}:{})});
 return <main className="work-page"><div className="page-heading"><p className="eyebrow">RECEPCIÓN · HORA CENTRO DE MÉXICO</p><h1>Tu agenda, a la vista</h1><p>Abre una cita para registrar la llegada, reprogramar o cerrar la atención.</p></div>
 <form className="filter-bar"><label>Fecha<input type="date" name="date" defaultValue={from}/></label><label>Sucursal<select name="branch" defaultValue={q.branch||''}><option value="">Mis sucursales autorizadas</option>{b.data.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><input type="hidden" name="view" value={week?'week':'day'}/><button className="button button-primary">Consultar</button></form>
 <nav className="toolbar" aria-label="Navegación de agenda"><div className="toolbar"><Link className="button button-secondary" href={url(addDays(from,week?-7:-1))}>← Anterior</Link><Link className="button button-secondary" href={url(todayMX())}>Hoy</Link><Link className="button button-secondary" href={url(addDays(from,week?7:1))}>Siguiente →</Link></div><div className="toolbar"><Link className={'button '+(!week?'button-primary':'button-secondary')} href={url(from,'day')}>Día</Link><Link className={'button '+(week?'button-primary':'button-secondary')} href={url(from,'week')}>Semana</Link></div></nav>
 <p className="muted">{rows.length} citas en el intervalo · {rows.filter(x=>x.checked_in_at&&['pending','confirmed'].includes(x.status)).length} pacientes en espera</p>{(r.data?.length||0)>500&&<p role="alert">Hay más de 500 citas. Filtra por día o sucursal.</p>}
 <div className={week?'week-grid':'day-grid'}>{days.map(day=><section className="agenda-day" key={day}><h2>{new Date(day+'T12:00:00Z').toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'short',timeZone:TZ})}</h2>{rows.filter(x=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ}).format(new Date(x.starts_at))===day).map((x:any)=><Link key={x.id} href={'/admin/citas/'+x.id} className={'appointment-card state-'+x.status}><span className="appointment-time">{new Date(x.starts_at).toLocaleTimeString('es-MX',{timeZone:TZ,hour:'2-digit',minute:'2-digit'})}</span><strong>{x.patients?.full_name||'Paciente'}</strong><span>{x.branches?.name}</span><span className="status-pill">{x.checked_in_at&&['pending','confirmed'].includes(x.status)?'En espera':states[x.status]}</span><small>{x.folio}</small></Link>)}{!rows.some(x=>new Intl.DateTimeFormat('en-CA',{timeZone:TZ}).format(new Date(x.starts_at))===day)&&<p className="empty-state">Sin citas para este día.</p>}</section>)}</div>
 </main>;
}
