'use client';
import {useState} from 'react';
import {createClient} from '@/lib/supabase/client';
export function SecurityForm({verified,aal2}:{verified:{id:string;friendly_name?:string}[],aal2:boolean}){
 const [factor,setFactor]=useState(verified[0]?.id||'');const [qr,setQr]=useState('');const [secret,setSecret]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function enroll(){setBusy(true);setMessage('');try{const s=createClient();const existing=await s.auth.mfa.listFactors();if(existing.error)throw existing.error;for(const f of existing.data.all.filter(x=>x.status==='unverified'))await s.auth.mfa.unenroll({factorId:f.id});const r=await s.auth.mfa.enroll({factorType:'totp',friendlyName:'GUBIA '+new Date().toISOString().slice(0,10)});if(r.error)throw r.error;setFactor(r.data.id);setQr(r.data.totp.qr_code);setSecret(r.data.totp.secret);}catch{setMessage('No se pudo preparar el autenticador. Intenta nuevamente.');}finally{setBusy(false);}}
 async function verify(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const code=String(new FormData(e.currentTarget).get('code')||'');try{const r=await createClient().auth.mfa.challengeAndVerify({factorId:factor,code});if(r.error)throw r.error;location.assign('/seguridad');}catch{setMessage('Código incorrecto o vencido. Usa el código actual del autenticador.');}finally{setBusy(false);}}
 async function password(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const password=String(f.get('password'));if(password!==f.get('repeat')){setMessage('Las contraseñas no coinciden.');return;}setBusy(true);try{const r=await createClient().auth.updateUser({password});if(r.error)throw r.error;setMessage('Contraseña actualizada.');(e.target as HTMLFormElement).reset();}catch{setMessage('No se pudo cambiar la contraseña. Si tu sesión es antigua, vuelve a iniciar sesión e inténtalo.');}finally{setBusy(false);}}
 return <div className="form-stack">{message&&<p role="status" className="form-alert">{message}</p>}<section className="card panel-pad"><h2>Verificación en dos pasos</h2><p>Protege tu cuenta con una aplicación autenticadora. Es obligatoria para crear cuentas o modificar accesos.</p>{aal2?<p className="success-note">Tu sesión está verificada con doble factor.</p>:<>{!factor&&<button className="button button-primary" disabled={busy} onClick={enroll}>Configurar autenticador</button>}{qr&&<><img src={qr} alt="Código QR para configurar tu autenticador" width={220} height={220}/><details><summary>Configurar manualmente</summary><code className="secret-code">{secret}</code></details><p>Guarda el acceso a tu autenticador. Si lo pierdes, necesitarás al responsable del proyecto para recuperar la cuenta.</p></>}{factor&&<form onSubmit={verify} className="form-stack"><label>Código de seis dígitos<input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" required/></label><button disabled={busy} className="button button-primary">{busy?'Verificando…':'Verificar código'}</button></form>}</>}</section><section className="card panel-pad"><h2>Cambiar contraseña</h2><p>Elige una contraseña única de al menos 12 caracteres.</p><form onSubmit={password} className="form-stack"><label>Nueva contraseña<input name="password" type="password" minLength={12} maxLength={128} autoComplete="new-password" required/></label><label>Repetir contraseña<input name="repeat" type="password" minLength={12} maxLength={128} autoComplete="new-password" required/></label><button disabled={busy} className="button button-primary">Actualizar contraseña</button></form></section></div>;
}
