import {requireStaff} from '@/lib/auth';
import Link from 'next/link';
import {createMember,updateMember} from './actions';
import {SubmitButton} from '@/components/submit-button';
export default async function Team({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const q=await searchParams;const {supabase,profile}=await requireStaff('team:manage');const [members,branches,assurance]=await Promise.all([supabase.from('profiles').select('id,full_name,role,active,branch_id').order('created_at').limit(501),supabase.from('branches').select('id,name').eq('active',true).order('name'),supabase.auth.mfa.getAuthenticatorAssuranceLevel()]);if(members.error||branches.error||assurance.error)throw Error('No se pudo cargar el equipo.');
 const roles=profile.role==='superadmin'?['administrador','recepcion','marketing','consulta']:['recepcion','marketing','consulta'];const verified=assurance.data.currentLevel==='aal2';
 const fields=(role='recepcion',branch='')=><><label>Rol<select name="role" defaultValue={role}>{roles.map(r=><option key={r} value={r}>{r}</option>)}</select></label><label>Sucursal (obligatoria para recepción y consulta)<select name="branch_id" defaultValue={branch}><option value="">Selecciona una sucursal</option>{branches.data.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></>;
 return <main className="work-page"><div className="page-heading"><p className="eyebrow">ADMINISTRACIÓN</p><h1>Equipo y accesos</h1><p>Recepción y consulta solo pueden ver información clínica de su sucursal. Marketing no puede leer pacientes.</p></div>{q.error&&<p className="form-alert" role="alert">{q.error}</p>}{q.saved&&<p className="success-note" role="status">Acceso guardado.</p>}{!verified&&<p className="form-alert">Para modificar cuentas, <Link href="/seguridad" className="underline">configura o verifica el doble factor</Link>.</p>}
 <details className="card panel-pad"><summary>Crear cuenta de personal</summary><form action={createMember} className="form-stack"><fieldset disabled={!verified}><label>Nombre completo<input name="name" maxLength={150} required/></label><label>Correo<input name="email" type="email" maxLength={254} required autoComplete="off"/></label><label>Contraseña inicial (12 caracteres como mínimo)<input name="password" type="password" minLength={12} maxLength={128} required autoComplete="new-password"/></label>{fields()}<p>La cuenta se activa directamente. Entrega las credenciales por un canal privado y pide cambiar la contraseña al ingresar. No se envía correo automáticamente.</p><SubmitButton>Crear cuenta</SubmitButton></fieldset></form></details>
 <div className="work-grid section-space">{members.data.map(m=><section className="card panel-pad" key={m.id}><h2>{m.full_name||'Personal'}</h2><span className="status-pill">{m.active?'Activo':'Desactivado'} · {m.role}</span>{m.id===profile.id?<p>Tu cuenta. Cambia tu contraseña en Seguridad.</p>:roles.includes(m.role)?<form action={updateMember} className="form-stack"><input type="hidden" name="id" value={m.id}/><fieldset disabled={!verified}>{fields(m.role,m.branch_id||'')}<label className="check-label"><input type="checkbox" name="active" defaultChecked={m.active}/>Cuenta activa</label><SubmitButton>Guardar permisos</SubmitButton></fieldset></form>:<p>Esta cuenta requiere un administrador de mayor nivel.</p>}</section>)}</div>{members.data.length>500&&<p>Se muestran los primeros 501 registros. Contacta al responsable técnico para revisar el directorio completo.</p>}</main>;
}
